project_name: pacm

before:
  hooks:
    - go generate

builds:
  - binary: pacm

    main: .
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/darki73/pac-manager/pkg/version.version={{.Version}} -X github.com/darki73/pac-manager/pkg/version.commit= -X github.com/darki73/pac-manager/pkg/version.commit={{.Commit}} -X github.com/darki73/pac-manager/pkg/version.buildDate={{.Date}} -X github.com/darki73/pac-manager/pkg/version.builtBy=goreleaser
    flags:
      - -trimpath
    goos:
      - linux

    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm

changelog:
  skip: true

archives:
  - id: pacm
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

release:
  disable: true